(() => {
'use strict';
const D=window.EDULAB, main=document.getElementById('content'), KEY='gyeongmin-edulab-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!D?.ready||!Array.isArray(D.candidates)||!D.candidates.length){main.innerHTML='<section id="loadError" class="panel" role="alert"><h1>학습 자료를 불러오지 못했어요.</h1><p>인터넷 연결을 확인한 뒤 새로고침해 주세요. 기존 학습 기록은 지우지 않았습니다.</p><button onclick="location.reload()">다시 불러오기</button></section>';return;}
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const isObject=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
const validId=id=>D.candidates.some(t=>t.id===id);
function cleanRecord(r){
  if(!isObject(r))return null;
  const out={};
  if(typeof r.answer==='string')out.answer=r.answer.slice(0,100000);
  for(const key of ['last','due'])if(typeof r[key]==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(r[key])&&!isNaN(Date.parse(r[key])))out[key]=r[key];
  if([0,1,2].includes(r.grade))out.grade=r.grade;
  for(const key of ['foundations','checks'])if(isObject(r[key]))out[key]=Object.fromEntries(Object.entries(r[key]).filter(([k,v])=>/^\d$/.test(k)&&Number(k)<(key==='checks'?5:2)&&(key==='checks'?typeof v==='boolean':[0,1].includes(v))));
  return out;
}
let state={version:1,topics:{},minutes:60,studyMode:'learn'},view='study',topicId=D.candidates[0].id,search='',domain='전체',year='전체',level='secondary',revealed=false,remaining=600,duration=600,running=false,timer,storageOkay=true,pendingImport=null,previousFocus=null;
try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p?.version===1&&isObject(p.topics)){state.minutes=[30,60,90].includes(p.minutes)?p.minutes:60;state.studyMode=p.studyMode==='recall'?'recall':'learn';if(typeof p.libraryRoot==='string')state.libraryRoot=p.libraryRoot;if(validId(p.lastTopic))state.lastTopic=p.lastTopic;for(const [id,r]of Object.entries(p.topics)){const clean=cleanRecord(r);if(validId(id)&&clean)state.topics[id]=clean;}}}catch(e){if(e.name!=='SyntaxError')storageOkay=false;}
if(state.lastTopic)topicId=state.lastTopic;
let lessonDomain='교육행정';
const routes=['study','practice','exams','policy','library','record','guide','lesson'];
const getTopic=()=>D.candidates.find(t=>t.id===topicId)||D.candidates[0];
const record=t=>state.topics[t.id]||{};
const source=(url,title)=>url&&/^https?:\/\//.test(url)?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`:esc(title);
const subjectKey=d=>({"교육행정":"admin","교육과정":"curriculum","교수학습":"learning","교육공학":"technology","교육평가":"assessment"}[d]||"other");
const tags=xs=>(xs||[]).map(x=>`<span class="tag" data-subject="${subjectKey(x)}">${esc(x)}</span>`).join(' ');
const intro=(k,t,p)=>`<div class="intro"><span class="eyebrow">${esc(k)}</span><h1 tabindex="-1">${esc(t)}</h1><p>${p||''}</p></div>`;
const subjects=[['교육행정','admin','함께 가르치는 학교'],['교육과정','curriculum','무엇을, 왜 가르칠까'],['교수학습','learning','이해가 일어나는 수업'],['교육공학','technology','도구를 배움으로 연결하기'],['교육평가','assessment','배움을 확인하는 증거']];
const iconPaths={admin:'M12 53V27l20-15 20 15v26M7 53h50M23 53V37h18v16M28 26h8',curriculum:'M9 13h17l6 5 6-5h17v39H38l-6 4-6-4H9zM32 18v38M16 25h10m-10 8h10m12-8h10m-10 8h10',learning:'M23 41h18M25 47h14M28 53h8M22 37c-14-13-3-31 10-31s24 18 10 31M32 2v-1M6 22H1m62 0h-5',technology:'M8 10h48v34H8zM21 54h22M32 44v10M17 28h10l6-9 7 16 7-7',assessment:'M14 10h36v46H14zM24 6h16v9H24zM22 30l6 6 14-14M22 45h20'};
const subjectIcon=key=>`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[key]}"></path></svg>`;
const focusGroups=[{title:'교육과정의 실제 구현',ids:[1,2],why:'2026 적용 확대와 2027 중3·고3 적용을 앞두고, 정합성·교사 재구성·숙의를 연결합니다.'},{title:'고교학점제와 최소 성취 지원',ids:[13],why:'2026 이수 기준 변화가 있습니다. 완전학습·형성평가·보충 지도로 풀어 씁니다.'},{title:'수행평가와 AI 활용 관리',ids:[4],why:'결과물만으로 이해를 판단하지 않도록 루브릭·타당도·신뢰도와 과정 증거를 연습합니다.'},{title:'AI 자료의 수업설계와 선정',ids:[8,21],why:'상호작용과 학습자 참여, 학교의 자료 선정과 개인정보 보호를 함께 봅니다.'},{title:'학생맞춤통합지원',ids:[19],why:'2026 시행 정책을 협력적 조직·역할 분담·사례 관리로 연결합니다. 빈출 이론과 함께 볼 후보입니다.'}];
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',4500);}
function updateStorageStatus(){const warning=document.getElementById('storageWarning');if(warning)warning.hidden=storageOkay;const s=document.getElementById('saveStatus');if(s){s.textContent=storageOkay?'이 브라우저에 저장됨':'저장 실패 · 지금 기록을 내보내세요';s.classList.toggle('error',!storageOkay);}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOkay=true;}catch{storageOkay=false;}updateStorageStatus();return storageOkay;}
function stopTimer(reset=false){running=false;clearInterval(timer);if(reset)remaining=duration;}
function focusMain(){main.querySelector('h1')?.focus({preventScroll:true});main.scrollIntoView?.({block:'start',behavior:'instant'});}
function navigate(v,focus=true){if(!routes.includes(v))v='study';if(view==='practice'&&v!=='practice')stopTimer();view=v;search='';domain='전체';document.querySelectorAll('nav button').forEach(b=>{const active=b.dataset.view===(v==='lesson'?'study':v);b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});render();location.hash=v;if(focus)focusMain();}
function startTopic(id){if(!validId(id))return;stopTimer(true);topicId=id;state.lastTopic=id;save();revealed=false;navigate('practice');}
function openLesson(d){lessonDomain=d;navigate('lesson');}
function learningPlan(){const due=D.candidates.filter(t=>record(t).due&&record(t).due<=today());const weak=D.candidates.filter(t=>Object.values(record(t).foundations||{}).includes(0));const first=subjects.map(([d])=>D.candidates.find(t=>t.domain===d&&t.mustReview&&!record(t).last)).filter(Boolean);return [...new Map([...due,...first,...weak,...D.candidates.filter(t=>!record(t).last),...D.candidates].map(t=>[t.id,t])).values()].slice(0,state.minutes/10);}
const filtered=()=>D.candidates.filter(t=>(domain==='전체'||t.domain===domain)&&(!search.trim()||JSON.stringify(t).toLowerCase().includes(search.trim().toLowerCase())));
function topicCard(t){const r=record(t);return `<article class="topic"><span class="tag priority">${esc(t.priority)} · ${t.rank}순위</span><h3>${esc(t.title)}</h3>${tags([t.domain])}<p>${esc(t.why)}</p><details><summary>기출·정책 근거 보기</summary><p>${esc(t.past.join(' · ')||'직접 대응 기출 미확인')}</p><p>${esc(t.policyStrength)}</p><p>${esc(t.caveat)}</p></details><p class="muted">${r.last?'최근 연습 '+esc(r.last):'아직 연습 전'}</p><button data-topic="${t.id}">이 주제 연습 →</button></article>`;}
function study(){
  const plan=learningPlan(),count=D.candidates.filter(t=>record(t).last).length,due=D.candidates.filter(t=>record(t).due&&record(t).due<=today()).length;
  main.innerHTML=`<section class="hero"><div class="hero-copy"><span class="hero-kicker">2027 SECONDARY TEACHER EXAM</span><h1 tabindex="-1">교육학, 오늘은<br>한 단원부터.</h1><p>개념을 이해하고, 내 말로 써 보는 10분.<br>빈출 다섯 단원과 올해의 정책을 차근차근 연결해요.</p><div class="hero-actions"><button class="primary" data-topic="${plan[0].id}">오늘의 첫 10분 시작 <span aria-hidden="true">↗</span></button><button data-nav="guide">처음이라면 사용법</button></div><div class="hero-notes"><span>10개년 기출</span><span>25개 대비 주제</span><span>50개 개념 점검</span></div></div><div class="hero-art" aria-hidden="true"><span>2027</span><i></i><b>한 단원씩, 확실하게.</b></div></section>
  <div class="study-dashboard"><section class="panel session-card"><div class="session-top"><div><span class="eyebrow">TODAY'S PLAN</span><h2>오늘의 학습 순서</h2></div><label>공부 시간 <select id="minutes">${[30,60,90].map(m=>`<option value="${m}" ${state.minutes===m?'selected':''}>${m}분</option>`).join('')}</select></label></div><p class="muted">개념 2분 → 답안 5분 → 점검 3분 · 복습 예정 ${due}개</p><ol class="session-list">${plan.map(t=>`<li>${tags([t.domain])}<button data-topic="${t.id}">${esc(t.title)} <span aria-hidden="true">→</span></button>${record(t).due&&record(t).due<=today()?'<span class="tag priority">복습</span>':''}</li>`).join('')}</ol></section><section class="panel starter-panel"><span class="eyebrow">작게 시작해도 괜찮아요</span><h2>앱이 처음이라면</h2><div class="guide-step"><span class="guide-step-number">1</span><p>위의 <b>첫 10분 시작</b>을 누르세요.<br>교재 폴더 설정 없이 시작할 수 있어요.</p></div><div class="guide-step"><span class="guide-step-number">2</span><p><b>처음 배워요</b>로 개념을 읽고,<br>학교 사례에 맞춰 3~5문장을 써요.</p></div><div class="guide-step"><span class="guide-step-number">3</span><p>예시와 비교한 뒤 기억 상태를 남겨요.<br>내일 다시 볼 내용은 앱이 모아줘요.</p></div><button data-nav="guide">버튼부터 알려주는 단계별 설명서 →</button><p class="muted">지금까지 ${count} / 25개 주제를 연습했어요.<br>연습 수는 숙달 점수와 다릅니다.</p></section></div>
  <section><div class="section-heading"><div><span class="eyebrow">FIVE ESSENTIALS</span><h2>빈출 5단원 · 필수 1회독</h2></div><span class="muted">핵심 설명 → 개념 구별 → 짧은 답안</span></div><div class="subject-grid">${subjects.map(([d,key,sub],i)=>{const xs=D.candidates.filter(t=>t.domain===d&&t.mustReview),done=xs.filter(t=>record(t).last).length;return `<article class="subject-card" data-subject="${key}"><div class="subject-art">${subjectIcon(key)}<span class="subject-number">0${i+1}</span></div><div class="subject-body"><p class="subject-meta">${esc(sub)}</p><h3 class="subject-title">${d}</h3><div class="progress" aria-label="${done}개 연습 기록"><span style="width:${done/xs.length*100}%"></span></div><p class="muted">필수 ${xs.length}개 중 ${done}개 연습</p><button data-lesson="${d}">핵심 설명부터 읽기 →</button></div></article>`}).join('')}</div></section>
  <section><div class="section-heading"><div><span class="eyebrow">2027 FOCUS</span><h2>올해, 한 번은 연결해 볼 주제</h2></div><button data-nav="policy">정책 근거 확인 →</button></div><p class="muted">반복 기출과 공개된 정책을 함께 살펴 고른 후보입니다. 각 주제에서 예상 이유와 근거의 강도를 확인하세요.</p><div class="course-grid">${focusGroups.map((f,i)=>`<article class="focus-card"><span class="topic-number">FOCUS 0${i+1}</span><h3>${esc(f.title)}</h3><p>${esc(f.why)}</p><div class="actions">${D.candidates.filter(t=>f.ids.includes(t.rank)).map(t=>`<button data-topic="${t.id}">${esc(t.title)} →</button>`).join('')}</div></article>`).join('')}</div></section>
  <details class="panel"><summary>나머지 출제 범위도 놓치지 않기</summary><p>공식 9개 범위를 안내하며, 아래 내용은 짧은 기본 확인입니다. 전체 교육학 이론을 빠짐없이 설명하는 완결 교재는 아닙니다.</p>${safetyNet()}</details>
  <details class="panel" id="allCandidates"><summary>전체 후보 25개 · 검색해서 골라보기</summary><div class="toolbar"><input id="search" type="search" placeholder="이론 · 정책 · 주제 검색" aria-label="후보 검색"><select id="domain" aria-label="영역 선택"><option>전체</option>${[...new Set(D.candidates.map(t=>t.domain))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><section id="cards" class="card-grid">${filtered().map(topicCard).join('')}</section></details>
  <details class="panel"><summary>왜 이 단원부터? 10년 배점 분석 보기</summary><p>40개 내용 블록 · 합계 150점. 학습심리를 교수학습·공학에 묶은 분석입니다.</p><div class="bars">${D.distribution.map(x=>`<div><label>${esc(x.domain)}</label><meter min="0" max="50" value="${x.percent}">${x.percent}%</meter><b>${x.percent}%</b></div>`).join('')}</div><p class="muted">구성·표현 5점은 매년 별도입니다. 영역 분류는 공식 가중치가 아닌 분석자의 분류입니다. 교육평가는 독립된 요구가 9개년에서 확인됩니다.</p><button data-nav="exams">기출 원문과 요구 보기 →</button></details>`;
}
function safetyNet(){return (D.lessons?.safetyNet||[]).map(x=>`<details><summary>${esc(x.domain)} · ${esc(x.title)}</summary><p>${esc(x.explanation)}</p><b>${esc(x.question)}</b><p>${esc(x.answer)}</p><div class="actions">${(x.relatedTopicIds||[]).filter(validId).map(id=>`<button data-topic="${id}">${esc(D.candidates.find(t=>t.id===id).title)}</button>`).join('')}</div></details>`).join('');}
function lesson(){const l=D.lessons?.domains?.find(x=>x.domain===lessonDomain);const xs=D.candidates.filter(t=>t.domain===lessonDomain);main.innerHTML=intro('핵심 설명',l?.title||lessonDomain,l?.lead||'아래 주제에서 개념을 먼저 읽고 짧은 답안을 써 보세요.')+`<p>${tags([lessonDomain])}</p><div class="actions"><button data-nav="study">← 학습 홈</button><button data-nav="guide">공부 방법 보기</button></div>${l?`<section class="panel subject-lesson"><h2>${esc(l.domain)}의 기본 개념</h2>${l.concepts.map((c,i)=>`<article class="reading"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${esc(c.term)}</h3><p>${esc(c.meaning)}</p><p><b>학교에서는</b> ${esc(c.example)}</p><p class="notice"><b>이렇게 구별해요</b> ${esc(c.contrast)}</p></article>`).join('')}</section><section class="panel lesson-example"><h2>짧은 답안, 이렇게 바꿔 보세요</h2><p class="notice">${esc(l.workedExample.situation)}</p><h3>보완할 답안</h3><p>${esc(l.workedExample.weakAnswer)}</p><h3>더 구체적인 답안</h3><p class="big-answer">${esc(l.workedExample.betterAnswer)}</p><p>${esc(l.workedExample.why)}</p><h3>내 답안의 뼈대</h3><p class="callout">${esc(l.answerFrame)}</p><h3>자주 하는 혼동</h3><ul>${l.commonMistakes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}<section class="panel"><h2>이제 한 주제씩 연습해요</h2><p>필수 주제부터 시작하고, 익숙해지면 연결 심화까지 넓히세요.</p><div class="card-grid">${xs.map(topicCard).join('')}</div></section>`;}
function reading(t){return(t.readings||[]).map(r=>`<div class="reading"><span class="tag">${r.verified?'본문 확인':'자동 개념어 색인'}</span><h3>${esc(r.name)}</h3><p>${esc(r.location)}</p><p class="muted">${esc(r.matchNote||'')}</p><p class="library-path">${esc(r.path)}</p><button data-copy="${esc(r.path)}">자료 위치 복사</button></div>`).join('')||'<p class="muted">자료실에서 개념어로 검색하세요.</p>';}
function practice(){
 const t=getTopic(),r=record(t),learn=state.studyMode!=='recall';
 main.innerHTML=intro('10분씩 · 이해하고 써보기',t.title,'오늘의 목표: 핵심 개념을 구별하고 학교 사례에 맞는 3~5문장을 직접 쓰기.')+`<p>${tags([t.domain])}</p><div class="toolbar"><button data-nav="study">← 학습 홈</button><label>주제 <select id="topicSelect">${D.candidates.map(x=>`<option value="${x.id}" ${t.id===x.id?'selected':''}>${x.rank}. ${esc(x.title)}</option>`).join('')}</select></label><button data-nav="guide">연습 방법</button></div><div class="sticky-practice-bar"><div class="study-mode" role="group" aria-label="공부 방식"><button data-mode="learn" aria-pressed="${learn}" class="${learn?'active':''}">처음 배워요</button><button data-mode="recall" aria-pressed="${!learn}" class="${!learn?'active':''}">기억을 꺼내요</button></div><div class="actions"><select id="duration" aria-label="연습 시간">${[600,1200,3600].map(v=>`<option value="${v}" ${duration===v?'selected':''}>${v/60}분 연습</option>`).join('')}</select><span id="timer" class="timer" aria-label="남은 시간">${clockText()}</span><button id="timerToggle">${running?'일시정지':'타이머 시작'}</button><button id="timerReset">초기화</button></div></div><div class="stepper">${['개념 이해','기억에서 꺼내기','내 답안 쓰기','비교하고 복습'].map((x,i)=>`<button class="step" data-step="step${i+1}"><span class="step-number">${i+1}</span>${x}</button>`).join('')}</div>
 <div class="two-col"><div><section id="step1" class="panel"><span class="eyebrow">STEP 01 · 이해</span><h2>먼저 개념을 구별하기</h2><p>${learn?'설명을 읽고 학교 장면을 떠올리세요. 처음 배우는 개념은 타이머를 멈추고 읽어도 괜찮아요.':'답을 펼치기 전에 내 말로 설명해 보세요. 기억이 안 나면 ‘처음 배워요’로 바꿔 읽으세요.'}</p><button data-lesson="${esc(t.domain)}">${esc(t.domain)} 핵심 설명 읽기 →</button>${t.foundation.map((f,i)=>`<details ${learn?'open':''}><summary>${esc(f.question)}</summary><p>${esc(f.answer)}</p><p class="notice"><b>혼동 주의</b> ${esc(f.trap)}</p></details>`).join('')}</section>
 <section id="step2" class="panel"><span class="eyebrow">STEP 02 · 인출</span><h2>설명을 접고 한 문장으로 말해요</h2><p class="muted">‘인출’은 기억에서 꺼낸다는 뜻이에요. 방금 읽은 답을 보지 않고 설명할 수 있는지 확인하세요.</p>${t.foundation.map((f,i)=>`<div class="reading"><b>${esc(f.question)}</b><div class="actions"><button data-fid="${i}" data-fgrade="0">다시 볼 개념</button><button data-fid="${i}" data-fgrade="1">설명할 수 있음</button></div><p id="foundationStatus${i}" class="muted">현재 기록: ${r.foundations?.[i]===1?'설명 가능':r.foundations?.[i]===0?'복습 필요':'미점검'}</p></div>`).join('')}</section>
 <section id="step3" class="panel"><span class="eyebrow">STEP 03 · 적용</span><h2>예상 사례 발문</h2><p class="big-answer">${esc(t.prompt)}</p><details><summary>막힐 때 사용할 답안 틀</summary><p>“○○는 …을 뜻한다. 제시문에서 …이므로, 교사는 …해야 한다. 이를 통해 …을 기대할 수 있다.”</p><p>이 틀을 모든 문제에 똑같이 붙이지 말고, 요구한 정의·방법·이유·개수에 맞춰 바꾸세요.</p></details><div class="notice">① 요구한 개수 표시 ② 개념의 뜻 설명 ③ 제시문에 적용 ④ 방법마다 이유·효과 연결</div><div class="row"><label for="answer">내 답안</label><span id="saveStatus" class="save-status" role="status"></span></div><textarea id="answer" placeholder="완벽한 문장부터 쓰지 않아도 돼요. 개념 → 사례 적용 → 교사 행동 → 기대 효과를 3~5문장으로 써 보세요.">${esc(r.answer||'')}</textarea><p id="answerCount" class="muted">${(r.answer||'').length}자 · 이 연습은 전체 20점 논술의 한 부분입니다.</p></section>
 <section id="step4" class="panel"><span class="eyebrow">STEP 04 · 점검</span><h2>예시와 비교하고 다음 복습 잡기</h2><button class="primary" id="reveal">${revealed?'예시 답안 접기':'예시 답안 · 체크 기준 보기'}</button>${revealed?`<section class="reading"><h3>분석자가 작성한 예시 답안</h3><p class="big-answer">${esc(t.answer)}</p><p class="muted">공식 정답·채점기준이 아닙니다. 뜻이 같은 다른 표현도 가능합니다.</p></section><p>아래 내용을 <b>내 답안에 실제로 썼을 때만</b> 체크하세요. 앱이 답안의 정확성을 자동 채점하지는 않습니다.</p><div class="checklist">${t.checklist.map((x,i)=>`<label><input type="checkbox" data-check="${i}" ${r.checks?.[i]?'checked':''}> ${esc(x)}</label>`).join('')}</div><p id="checkCount" class="muted">${Object.values(r.checks||{}).filter(Boolean).length} / 5개 확인 · 시험 점수로 환산되지 않습니다.</p><h3>기억 상태는 어땠나요?</h3><p>설명을 보고 겨우 썼다면 ‘다시 보기’, 도움 없이 이유까지 썼다면 ‘잘 기억함’을 고르세요.</p><div class="actions"><button data-grade="0">다시 보기 · 내일</button><button data-grade="1">보통 · 3일 뒤</button><button data-grade="2">잘 기억함 · 7일 뒤</button></div><p id="gradeStatus" role="status">${r.due?'다음 복습: '+esc(r.due):''}</p><button id="nextTopic" ${r.last?'':'hidden'} class="primary">다음 주제로 →</button>`:''}</section></div>
 <aside><section class="panel"><h2>이 주제를 보는 이유</h2>${tags([t.domain,t.priority])}<p>${esc(t.why)}</p><details><summary>기출과 정책 근거 펼치기</summary><h3>기출 연결</h3><p>${esc(t.past.join(' · ')||'직접 대응 미확인')}</p><h3>정책 연결</h3><p>${esc(t.policyStrength)}</p><ul>${t.policy.map(x=>`<li>${source(x.url,x.title)} <small>${esc(x.note)}</small></li>`).join('')}</ul><p class="notice">${esc(t.caveat)}</p></details>${t.mackey?`<details><summary>맥키 자료와 연결</summary><p>${esc(t.mackey)}</p></details>`:''}</section><details class="panel"><summary>내 교재에서 읽을 곳</summary><p class="muted">본문 확인 위치를 먼저 봅니다. 자동 색인에는 목차·부수적 언급이 섞일 수 있습니다. PDF 쪽과 인쇄 쪽은 다를 수 있어요.</p>${reading(t)}<button data-nav="library">자료실 · 폴더 설정</button></details></aside></div>`;
}
function exams(){const xs=level==='secondary'?D.secondary:D.primary;main.innerHTML=intro('10년 기출','실제 요구를 연도별로 비교하기.','학년도와 실제 시험일을 분리했습니다. 초등은 교직논술, 중등은 교육학 논술입니다.')+`<div class="toolbar"><select id="examLevel" aria-label="학교급"><option value="secondary" ${level==='secondary'?'selected':''}>중등 교육학</option><option value="primary" ${level==='primary'?'selected':''}>초등 교직논술</option></select><select id="examYear" aria-label="학년도"><option>전체</option>${xs.map(x=>`<option ${year===String(x.year)?'selected':''}>${x.year}</option>`).join('')}</select><a href="downloads/exam-sources.json" download>20개 공식 기출 원문 목록</a><a href="downloads/secondary-analysis.md" download>중등 상세 분석</a><a href="downloads/primary-analysis.md" download>초등 상세 분석</a></div><div class="notice">${esc(level==='secondary'?D.secondaryNote:D.primaryNote)}</div>${xs.filter(x=>year==='전체'||String(x.year)===year).map(x=>`<section class="panel"><div class="row"><h2>${x.year}학년도 ${level==='secondary'?'교육학':'교직논술'}</h2><span class="tag">공식 원문</span></div><p class="muted">실제 시험일 ${esc(x.date)} · ${esc(x.theme)}</p><div class="actions"><a href="${esc(x.localPdf)}" target="_blank" rel="noopener">문제지 열기</a>${source(x.source,'KICE 게시물')}</div>${x.blocks.map(b=>`<article class="exam-block"><div class="row"><b>${esc(b.domain)} · ${esc(b.title)}</b><span>${esc(b.points)}점</span></div><p>${esc(b.demand)}</p>${b.theory?`<p class="muted">이론 해석: ${esc(b.theory)}</p>`:''}</article>`).join('')}<p>${esc(x.observation)}</p></section>`).join('')}<section class="panel"><h2>공식 출제 범위</h2><p>${esc(D.officialScope.join(' · '))}</p>${source('https://www.kice.re.kr/sub/info.do?m=010602&s=kice','KICE 중등교사임용시험 안내')}<p>순위가 낮은 영역도 개념·사례를 짧게 유지하세요.</p></section>`;}
function policy(){main.innerHTML=intro('정책 대조','정책의 시계와 시험의 시계를 따로 읽기.','발표·계획·시행을 구분하고 시험 당시 공개된 정책인지 확인합니다.')+`<div class="notice caution">${esc(D.policyConclusion)}</div><section class="panel"><h2>기출과 정책의 관계</h2><p class="muted">직접 언급 / 이론 연결 / 주제 유사 / 근거 부족을 구분합니다. 시간적 선후는 출제 의도를 입증하지 않습니다.</p><div class="table-wrap"><table><thead><tr><th>기출</th><th>정책 날짜와 근거</th><th>판단</th></tr></thead><tbody>${D.comparisons.map(x=>`<tr><td>${esc(x.exam)}<p class="muted">${esc(x.topic)}</p></td><td>${esc(x.dates)}<p>${source(x.url,x.policy)}</p></td><td><span class="tag">${esc(x.verdict)}</span><p>${esc(x.reason)}</p></td></tr>`).join('')}</tbody></table></div><a href="downloads/policy-analysis.md" download>정책 상세 분석</a> · <a href="downloads/content-audit.md" download>적용 대상·날짜 교차검토</a></section><section class="panel"><h2>정책 연표 · 발표와 시행</h2><div class="timeline">${D.policies.map(x=>`<article><b>${esc(x.date)} · ${esc(x.title)}</b><p>${esc(x.summary)}</p><p class="muted">시행·상태: ${esc(x.status)}</p>${source(x.url,x.sourceTitle||'공식 원문')}</article>`).join('')}</div></section>`;}

function libraryRows(){const q=search.trim().toLowerCase();const xs=D.library.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));return `<p class="muted">${xs.length}개 자료</p><div class="card-grid">${xs.map(x=>{const matches=Object.entries(x.hits||{}).filter(([term])=>q&&term.toLowerCase().includes(q));return `<article class="topic"><span class="tag">${esc(x.status)}</span><h3>${esc(x.name)}</h3><p class="muted">${x.pages?x.pages+'쪽 · ':''}${esc(x.group)}</p><p>${esc(x.topics.slice(0,10).join(' · ')||'주요 개념 자동 대응 없음')}</p>${matches.map(([term,ps])=>`<p><b>${esc(term)}</b> · PDF ${ps.slice(0,12).join(', ')}쪽${ps.length>12?' 외':''}</p>`).join('')}<p class="library-path">${esc(x.path)}</p><button data-copy="${esc(x.path)}">자료 위치 복사</button></article>`}).join('')||'<p class="empty">검색 결과가 없습니다. ‘형성평가’처럼 짧은 개념어로 찾아보세요.</p>'}</div>`;}
function library(){main.innerHTML=intro('내 자료실','내 교재를, 지금 배우는 개념 옆에.','앱 안의 학습부터 시작하고, 더 자세히 읽고 싶을 때 원래 교재를 찾아보세요.')+`<details class="panel"><summary>자료 범위와 검색 정확도</summary><p>${esc(D.libraryNote)}</p><p>원페이지 6판·2019 매메세 등은 이론 복습에 사용하고, 현행 정책은 공식 자료로 확인하세요. 자동 OCR·용어 색인은 전수 정독이나 모든 쪽의 내용 검증을 의미하지 않습니다.</p></details><details class="panel"><summary>교재를 읽을 때 주의할 표현 · 본문 대조 결과</summary><ul>${(D.lessons?.readingWarnings||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>특히 신뢰도와 형성평가의 과도한 단정은 앱의 핵심 설명과 함께 확인하세요.</p></details><section class="panel"><h2>내 교재 연결 · 처음 한 번만</h2><p>Windows에서 ‘클로드 작업 그룹 → 교육학’ 폴더를 열고, 주소창의 폴더 주소를 복사해 아래에 붙여넣으세요.</p><label for="libraryRoot">교육학 폴더 주소</label><div class="toolbar"><input id="libraryRoot" type="text" placeholder="파일 탐색기 주소창에서 복사한 폴더 주소" value="${esc(state.libraryRoot||'')}"><button id="saveLibraryRoot" class="primary">폴더 위치 저장</button><button data-guide="local-library">그대로 따라 할 설명 보기</button></div><p id="rootStatus" role="status" class="muted">${state.libraryRoot?'설정된 폴더: '+esc(state.libraryRoot):'설정 전이어도 개념 학습과 답안 연습은 가능합니다.'}</p><p class="muted">‘자료 위치 복사’ 후 파일 탐색기 주소창에 붙여넣어 여세요. 웹앱이 컴퓨터의 파일을 직접 열거나 업로드하지는 않습니다.</p></section><div class="toolbar"><input id="librarySearch" type="search" placeholder="파일명 · 개념어로 검색" aria-label="개인 자료 검색" value="${esc(search)}"><a href="downloads/library-map.json" download>전체 색인 내려받기</a></div><details class="panel"><summary>맥키 교수님 자료 5개 · 먼저 읽을 부분</summary>${D.mackey.map(x=>`<details><summary>${esc(x.title)}</summary><p>${esc(x.summary)}</p><h3>교육학으로 연결할 질문</h3><p>${esc(x.connection)}</p><p class="notice">${esc(x.limit)}</p><p class="library-path">${esc(x.path)}</p><button data-copy="${esc(x.path)}">자료 위치 복사</button></details>`).join('')}<a href="downloads/mackey-analysis.md" download>맥키 자료 상세 분석</a></details><section id="libraryResults">${libraryRows()}</section>`;}
function records(){const xs=D.candidates.filter(t=>record(t).answer||record(t).last||Object.keys(record(t).foundations||{}).length);main.innerHTML=intro('학습 기록','내가 쓴 문장이 쌓이는 곳.','같은 기기·같은 브라우저·같은 버전에서 이어 공부할 수 있어요.')+`<section class="panel"><h2>기록 보관과 기기 옮기기</h2><p>공부를 마치면 파일로 한 번 보관하세요. GitHub판과 Apps Script판, 휴대폰과 PC는 기록이 자동으로 합쳐지지 않습니다.</p><div class="actions"><button class="primary" id="export">학습 기록 내보내기</button><label class="file-label">기록 가져오기 <input id="import" type="file" accept="application/json,.json"></label><button data-guide="records-backup">백업 설명 보기</button></div><p class="muted">가져올 파일의 주제 수와 중복을 먼저 보여드립니다. 적용하기 전까지 현재 답안은 바뀌지 않습니다.</p></section>${xs.map(t=>{const r=record(t);return`<details><summary>${esc(t.title)} · ${esc(r.last||'작성 중')}</summary><p>다음 복습: ${esc(r.due||'미정')} · 개념 확인 ${Object.keys(r.foundations||{}).length}/2</p><pre>${esc(r.answer||'아직 쓴 답안이 없습니다.')}</pre><button data-topic="${t.id}">이어 연습하기 →</button></details>`}).join('')||'<section class="panel empty-state"><h2>첫 문장부터 남겨 보세요.</h2><p>연습 화면에 쓴 답안은 여기에서 다시 볼 수 있어요.</p><button class="primary" data-topic="${learningPlan()[0].id}">첫 10분 시작 →</button></section>'}`;}
function guide(){const g=D.guide||{quickStart:[],sections:[],faq:[]};main.innerHTML=intro('처음 쓰는 분을 위한 설명서','누를 버튼부터, 공부하는 방법까지.','처음부터 전부 읽지 않아도 괜찮아요. 첫 10분만 따라 하고, 필요한 설명을 나중에 찾아보세요.')+`<section class="panel"><h2>첫 공부는 이 네 단계면 됩니다</h2><div class="coverage-grid">${g.quickStart.map((x,i)=>`<article class="guide-step"><span class="guide-step-number">${i+1}</span><div><h3>${esc(x.title.replace(/^\d+\.\s*/,''))}</h3><p>${esc(x.body)}</p></div></article>`).join('')}</div><div class="actions"><button class="primary" data-topic="${learningPlan()[0].id}">설명 읽었어요 · 첫 10분 시작 →</button><button id="print">설명서 인쇄 / PDF로 저장</button></div></section><div class="guide-layout"><aside class="guide-toc"><h2>필요한 설명 찾기</h2>${g.sections.map(x=>`<button data-guide="${esc(x.id)}">${esc(x.title)}</button>`).join('')}<button data-step="guide-faq">자주 묻는 질문</button><button data-step="coverageStatus">어디까지 완성됐나요?</button></aside><div class="guide-content">${g.sections.map(x=>`<section id="guide-${esc(x.id)}" class="panel"><h2>${esc(x.title)}</h2><p>${esc(x.intro)}</p>${x.steps.map((st,i)=>`<article class="guide-step"><span class="guide-step-number">${i+1}</span><div><h3>${esc(st.title)}</h3><p>${esc(st.body)}</p></div></article>`).join('')}${(x.tips||[]).map(t=>`<p class="notice">${esc(t)}</p>`).join('')}</section>`).join('')}<section id="guide-faq" class="panel"><h2>자주 묻는 질문</h2>${g.faq.map(x=>`<details class="guide-faq"><summary>${esc(x.question)}</summary><p>${esc(x.answer)}</p></details>`).join('')}</section><section id="coverageStatus" class="panel"><h2>무엇을 담았고, 어디까지 확인했나요?</h2><ul><li>2017~2026학년도 초·중등 공식 기출 각 10개와 요구·배점 분석</li><li>정책 연표 ${D.policies.length}개와 기출·정책 대조 ${D.comparisons.length}개. 시간 순서와 출제 의도를 구분</li><li>우선 후보 25개, 개념 질문 50개, 자체 예시답안·체크 기준</li><li>다섯 핵심 단원 입문 설명과 다른 범위의 짧은 개념 확인</li><li>개인 자료 자동 색인 및 맥키 지정 자료 5개 분석</li></ul><p class="notice">두 번째 Drive 계정 전체 접근은 확인하지 못했습니다. 개인 자료 전체를 수동 정독한 결과는 아니며, 자동 색인의 쪽수에는 목차 등이 포함될 수 있습니다. ‘본문 확인’ 표시가 있는 위치부터 읽으세요.</p><p>이 앱은 2027 대비를 돕는 학습 도구입니다. 출제 적중·점수 향상을 보장하거나 전체 교육학 교재와 교사의 답안 피드백을 모두 대체하지는 않습니다. 정책 기준일은 ${esc(D.asOf)}입니다.</p></section></div></div>`;}
function render(){({study,practice,exams,policy,library,record:records,guide,lesson}[view]||study)();wire();updateStorageStatus();}
const clockText=()=>String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');
function exportRecords(){
 const text=JSON.stringify(state,null,2),filename='교육학-학습기록-'+today()+'.json';
 document.getElementById('exportFallback')?.remove();
 if(exportRecords.objectUrl){try{URL.revokeObjectURL(exportRecords.objectUrl);}catch{}exportRecords.objectUrl=null;}
 let url=null;
 try{url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'}));exportRecords.objectUrl=url;}catch{}
 const panel=document.createElement('details');panel.id='exportFallback';panel.className='panel';panel.open=true;
 panel.innerHTML=`<summary>내보낸 기록 · 파일 저장 확인</summary><p>파일 이름: <b>${esc(filename)}</b></p><p>브라우저의 다운로드 목록이나 다운로드 폴더에 파일이 생겼는지 확인해 주세요. 이 앱은 실제 파일 저장 완료를 확인할 수 없습니다.</p>${url?`<p><a id="backupDownload" href="${esc(url)}" download="${esc(filename)}">파일이 없다면 직접 내려받기</a></p>`:'<p class="notice">이 브라우저에서는 파일 만들기가 제한됩니다. 아래의 기록 내용을 복사해 보관해 주세요.</p>'}<div class="actions"><button id="selectBackupText">기록 내용 전체 선택</button><button id="copyBackupText">기록 내용 복사</button></div><p id="backupStatus" role="status" class="muted">복사만으로 파일이 저장되는 것은 아닙니다. 파일을 받았거나 다른 곳에 내용을 붙여넣어 보관한 것을 확인한 뒤 이 화면을 닫으세요.</p><details id="backupManual"><summary>파일 저장이 안 될 때 · 기록 내용으로 보관하기</summary><p>전체 선택 뒤 Ctrl+C로 복사하고 Windows 메모장에 붙여넣으세요. ‘다른 이름으로 저장’에서 위 파일 이름, 파일 형식 ‘모든 파일’, 인코딩 UTF-8로 저장하면 ‘기록 가져오기’에 쓸 수 있습니다. 휴대전화에서는 선택한 내용을 복사해 메모 등에 먼저 보관하고, 나중에 PC에서 .json 파일로 저장하세요. 아래 내용은 직접 수정하지 마세요.</p><label for="backupJson">내보낸 기록 내용 (JSON)</label><textarea id="backupJson" readonly rows="8" spellcheck="false">${esc(text)}</textarea></details>`;
 const host=document.querySelector('[role="dialog"]')||main;
 if(host===main)host.prepend(panel);else host.append(panel);
 const select=()=>{panel.querySelector('#backupManual').open=true;const box=panel.querySelector('#backupJson');box.focus();box.select();};
 panel.querySelector('#selectBackupText').onclick=()=>{select();panel.querySelector('#backupStatus').textContent='전체 내용을 선택했어요. Ctrl+C 또는 기기의 복사 메뉴로 복사한 뒤 메모장 등에 붙여넣어 보관하세요.';};
 panel.querySelector('#copyBackupText').onclick=async()=>{try{await navigator.clipboard.writeText(text);panel.querySelector('#backupStatus').textContent='기록 내용을 복사했어요. 메모장 등에 붙여넣고 파일로 저장해야 보관이 완료됩니다.';}catch{select();panel.querySelector('#backupStatus').textContent='자동 복사가 제한되어 전체 내용을 선택했어요. Ctrl+C 또는 기기의 복사 메뉴로 복사한 뒤 다른 곳에 붙여넣어 보관하세요.';}};
 if(url){const a=document.createElement('a');a.href=url;a.download=filename;a.hidden=true;document.body.append(a);try{a.click();}catch{panel.querySelector('#backupStatus').textContent='자동 내려받기를 시작하지 못했어요. 위의 직접 내려받기 링크 또는 기록 내용 복사를 이용하세요.';}finally{a.remove();}}
 panel.scrollIntoView?.({block:'nearest',behavior:'smooth'});
 toast('파일이 실제로 저장됐는지 확인해 주세요. 안 되면 화면의 내려받기 링크나 기록 내용 복사를 이용하세요.');
}
function grade(g){const t=getTopic();if(!(record(t).answer||'').trim()){toast('짧게라도 내 답안을 먼저 써 주세요.');document.getElementById('answer')?.focus();return;}const d=new Date();d.setDate(d.getDate()+[1,3,7][g]);state.topics[t.id]={...record(t),last:today(),due:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(d),grade:g};save();stopTimer();const s=document.getElementById('gradeStatus');if(s)s.textContent='연습을 기록했어요. 다음 복습: '+state.topics[t.id].due;document.getElementById('nextTopic').hidden=false;document.getElementById('timerToggle').textContent='타이머 시작';toast('기록했어요. 다음 주제로 가거나 답안을 더 다듬을 수 있어요.');}
function dialog(html){previousFocus=document.activeElement;document.getElementById('dialogHost').innerHTML=`<div class="dialog-overlay"><section class="dialog-card" role="dialog" aria-modal="true" aria-labelledby="dialogTitle" id="importPreview">${html}</section></div>`;document.getElementById('dialogHost').querySelector('button,textarea')?.focus();}
function closeDialog(){document.getElementById('dialogHost').innerHTML='';pendingImport=null;previousFocus?.focus();}
function scrollTo(id){const e=document.getElementById(id);if(e){e.scrollIntoView?.({block:'start',behavior:'smooth'});const h=e.querySelector('h2')||e;h.tabIndex=-1;h.focus({preventScroll:true});}}
async function copy(s){if(!/^[A-Z]:[\\/]|^\\\\/i.test(s)){if(!state.libraryRoot){navigate('library');toast('교육학 폴더 주소를 먼저 저장해 주세요. 아래 설명대로 한 번만 설정하면 됩니다.');document.getElementById('libraryRoot')?.focus();return;}s=state.libraryRoot.replace(/[\\/]+$/,'')+'\\'+s;}try{await navigator.clipboard.writeText(s);toast('복사했어요. Windows 파일 탐색기 주소창에 붙여넣고 Enter를 누르세요.');}catch{dialog(`<h2 id="dialogTitle">자료 위치를 직접 복사해 주세요</h2><p>이 브라우저에서는 자동 복사가 제한됩니다. 아래 주소를 선택해 복사하고, 파일 탐색기 주소창에 붙여넣으세요.</p><label for="copyPath">파일 위치</label><textarea id="copyPath" readonly>${esc(s)}</textarea><div class="dialog-actions"><button id="selectCopyPath">주소 전체 선택</button><button id="cancelImport">닫기</button></div>`);document.getElementById('selectCopyPath').onclick=()=>{document.getElementById('copyPath').select();};document.getElementById('cancelImport').onclick=closeDialog;}}
async function previewImport(file){try{if(!file||file.size>5000000)throw Error();const p=JSON.parse(await file.text());if(!isObject(p)||p.version!==1||!isObject(p.topics))throw Error();const clean={};for(const [id,r]of Object.entries(p.topics)){if(!validId(id))continue;if(!isObject(r)||('answer'in r&&typeof r.answer!=='string'))throw Error();const c=cleanRecord(r);if(c&&Object.keys(c).length)clean[id]=c;}const ids=Object.keys(clean);if(!ids.length){toast('가져올 수 있는 학습 기록이 0개입니다. 현재 기록은 그대로 두었습니다.');return;}pendingImport=clean;const overlap=ids.filter(id=>state.topics[id]&&Object.keys(state.topics[id]).length).length;dialog(`<h2 id="dialogTitle">가져올 기록을 확인하세요</h2><p>총 <b>${ids.length}개 주제</b>를 가져옵니다. 현재 기록과 겹치는 주제는 <b>${overlap}개</b>입니다.</p><p>같은 주제에 파일의 답안이 있으면 현재 답안이 바뀝니다. 파일에 없는 항목은 유지합니다.</p><div class="dialog-actions"><button id="backupBeforeImport">현재 기록 먼저 내보내기</button><button id="cancelImport">취소</button><button class="primary" id="confirmImport">확인 · 기록 적용</button></div>`);document.getElementById('backupBeforeImport').onclick=exportRecords;document.getElementById('cancelImport').onclick=closeDialog;document.getElementById('confirmImport').onclick=()=>{for(const [id,r]of Object.entries(pendingImport||{})){const old=state.topics[id]||{};state.topics[id]={...old,...r,foundations:{...(old.foundations||{}),...(r.foundations||{})},checks:{...(old.checks||{}),...(r.checks||{})}};}save();closeDialog();render();toast(ids.length+'개 주제의 기록을 적용했습니다.');};}catch{toast('학습 기록 내보내기로 만든 JSON 파일을 선택해 주세요. 현재 기록은 바뀌지 않았습니다.');}}
function wire(){
 const by=id=>document.getElementById(id);
 main.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));main.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic));main.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));main.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy));main.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>scrollTo(b.dataset.step));main.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{const id=b.dataset.guide;if(view!=='guide')navigate('guide');const fallback=D.guide?.sections?.find(x=>id==='local-library'?/자료|교재/.test(x.title):/기록|백업/.test(x.title));scrollTo('guide-'+(D.guide?.sections?.some(x=>x.id===id)?id:fallback?.id||D.guide?.sections?.[0]?.id));});
 main.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.studyMode=b.dataset.mode;save();render();});
 main.querySelectorAll('[data-fid]').forEach(b=>b.onclick=()=>{const t=getTopic();state.topics[t.id]={...record(t),foundations:{...(record(t).foundations||{}),[b.dataset.fid]:Number(b.dataset.fgrade)}};save();by('foundationStatus'+b.dataset.fid).textContent='현재 기록: '+(Number(b.dataset.fgrade)?'설명 가능':'복습 필요');toast(Number(b.dataset.fgrade)?'설명 가능으로 기록했어요.':'다음 공부에서 다시 볼 개념으로 기록했어요.');});
 if(by('search'))by('search').oninput=e=>{search=e.target.value;by('cards').innerHTML=filtered().map(topicCard).join('')||'<p class="empty">검색 결과가 없습니다.</p>';by('cards').querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic));};
 if(by('domain'))by('domain').onchange=e=>{domain=e.target.value;by('cards').innerHTML=filtered().map(topicCard).join('')||'<p class="empty">검색 결과가 없습니다.</p>';by('cards').querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic));};
 if(by('minutes'))by('minutes').onchange=e=>{state.minutes=Number(e.target.value);save();render();};if(by('print'))by('print').onclick=()=>window.print();if(by('topicSelect'))by('topicSelect').onchange=e=>startTopic(e.target.value);
 if(by('answer'))by('answer').oninput=e=>{const t=getTopic();state.topics[t.id]={...record(t),answer:e.target.value};save();by('answerCount').textContent=e.target.value.length+'자 · 이 연습은 전체 20점 논술의 한 부분입니다.';};
 if(by('reveal'))by('reveal').onclick=()=>{revealed=!revealed;render();scrollTo('step4');};main.querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>{const t=getTopic();state.topics[t.id]={...record(t),checks:{...(record(t).checks||{}),[b.dataset.check]:b.checked}};save();by('checkCount').textContent=Object.values(record(t).checks).filter(Boolean).length+' / 5개 확인 · 시험 점수로 환산되지 않습니다.';});main.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(Number(b.dataset.grade)));
 if(by('nextTopic'))by('nextTopic').onclick=()=>startTopic((learningPlan().find(t=>t.id!==topicId)||D.candidates[(D.candidates.findIndex(t=>t.id===topicId)+1)%D.candidates.length]).id);
 if(by('duration'))by('duration').onchange=e=>{duration=Number(e.target.value);stopTimer(true);render();};if(by('timerToggle'))by('timerToggle').onclick=()=>{if(!remaining)remaining=duration;running=!running;clearInterval(timer);if(running)timer=setInterval(()=>{remaining=Math.max(0,remaining-1);if(by('timer'))by('timer').textContent=clockText();if(!remaining){stopTimer();toast('연습 시간이 끝났어요. 답안을 점검해 보세요.');if(by('timerToggle'))by('timerToggle').textContent='타이머 시작';}},1000);by('timerToggle').textContent=running?'일시정지':'타이머 시작';};if(by('timerReset'))by('timerReset').onclick=()=>{stopTimer(true);render();};
 if(by('examLevel'))by('examLevel').onchange=e=>{level=e.target.value;year='전체';render();};if(by('examYear'))by('examYear').onchange=e=>{year=e.target.value;render();};
 if(by('librarySearch'))by('librarySearch').oninput=e=>{search=e.target.value;by('libraryResults').innerHTML=libraryRows();by('libraryResults').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy));};if(by('librarySearch'))by('librarySearch').onchange=by('librarySearch').oninput;
 if(by('saveLibraryRoot'))by('saveLibraryRoot').onclick=()=>{const s=by('libraryRoot').value.trim().replace(/^"|"$/g,'');if(!/^[A-Z]:[\\/]|^\\\\/i.test(s)){by('rootStatus').textContent='파일 탐색기에서 복사한 전체 폴더 주소를 입력해 주세요.';by('libraryRoot').focus();return;}state.libraryRoot=s;save();by('rootStatus').textContent='저장된 폴더: '+s;toast('이제 자료 위치를 복사해 파일 탐색기에서 열 수 있어요.');};
 if(by('export'))by('export').onclick=exportRecords;if(by('import'))by('import').onchange=e=>previewImport(e.target.files[0]);
}
document.querySelector('.brand').onclick=e=>{e.preventDefault();navigate('study');};document.querySelectorAll('nav button,[data-header-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.view||b.dataset.headerNav));document.getElementById('emergencyExport').onclick=exportRecords;
document.addEventListener('keydown',e=>{const dialogEl=document.querySelector('[role="dialog"]');if(!dialogEl)return;if(e.key==='Escape'){e.preventDefault();closeDialog();}if(e.key==='Tab'){const xs=[...dialogEl.querySelectorAll('button,textarea,input,a[href]')].filter(x=>!x.disabled);if(!xs.length)return;const first=xs[0],last=xs[xs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(v!==view&&routes.includes(v))navigate(v);});
window.addEventListener('error',()=>{const e=document.getElementById('appError');if(e)e.hidden=false;});
const h=location.hash.slice(1);navigate(routes.includes(h)?h:'study',false);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const t of [{name:'read_education_candidates',title:'교육학 후보 읽기',description:'우선순위와 근거를 포함한 후보 목록을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>D.candidates.map(t=>({id:t.id,rank:t.rank,title:t.title,domain:t.domain}))},{name:'start_education_practice',title:'인출 연습 열기',description:'주제의 연습 화면을 엽니다. 완료나 평가를 기록하지 않습니다.',inputSchema:{type:'object',properties:{topicId:{type:'string'}},required:['topicId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>{if(!i||typeof i.topicId!=='string')throw Error('주제 ID가 필요합니다.');startTopic(i.topicId);return{topicId,view:'practice'}}}])try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
window.EDULAB_ACTIONS={startTopic,readState:()=>JSON.parse(JSON.stringify(state))};
})();
